name: restaurant_mgr
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
         
  #font_awesome_flutter: ^8.5.0
  #firebase_storage: ^3.1.1
  #firebase_dynamic_links: ^0.5.0+9
  #http: "^0.11.3+17"
  firebase_database: ^3.1.1
  firebase_core: <2.0.0
  google_sign_in: ^3.2.1
  intl: ">=0.15.0 <1.0.0"
  cupertino_icons: ^0.1.2
  firebase_auth:  ^0.15.5+2
  #flushbar: ^1.5.0
  flushbar:
    git:
      url: git://github.com/valterh4ck3r/flushbar
      ref: master
  #fluttertoast: ^3.1.3
  #flutter_svg: ^0.6.1+1
  #flutter_screenutil: ^0.4.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.7.4

flutter_icons:
  ios: true
  android: true
  image_path: "assets/img/icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/img/restapp.png
